import streamlit as st
import pandas as pd
import base64
from pathlib import Path
from chartjsbubble import chartjs_plot
from variable_names import get_color_discrete_map, get_plot_and_hover_display_names, get_hover_data
import streamlit.components.v1 as components
from visualsetup import load_visual_identity

st.set_page_config(
    page_title="Mapa Příležitostí",
    page_icon="logo_notext.svg",
    layout="wide"
)
#Loading loads of custom css in markdown
load_visual_identity("header.jpg")

st.logo('logo_notext.svg',size='large',icon_image='logo_notext.svg')
logocol1,logocol2 = st.columns([2,3])
logocol1.image('logo_text.svg',use_container_width=True)
# Function to encode image to base64 (useful if deploying where paths might change)
# or just use relative paths if running locally and files are present.
@st.cache_data
def get_image_base64(path: str) -> str:
    try:
        with open(path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode()
    except FileNotFoundError:
        return "" # Return empty string or a placeholder base64 if file not found

# --- Main App ---
st.title("Vertically Centered Logos")

# --- Your Logo Section ---
logocol1, logocol2 = st.columns([2, 8]) # Adjusted ratio for better spacing maybe

with logocol1:
    # Vertically center the first logo too
    st.markdown("""
        <style>
        /* Target the container generated by Streamlit for the column */
        [data-testid="stVerticalBlock"] {
            display: flex;
            flex-direction: column;
            justify-content: center; /* Center vertically */
        }
        /* Ensure the image itself doesn't add extra weird spacing */
         [data-testid="stVerticalBlock"] img {
             display: block; /* Remove potential bottom space */
             margin: auto; /* Center horizontally if needed, works with block */
         }
        </style>
    """, unsafe_allow_html=True)
    # Ensure the path is correct relative to your script
    # For robustness, especially if deploying, consider absolute paths or checking existence
    logo_text_path = 'logo_text.svg'
    if Path(logo_text_path).is_file():
        st.image(logo_text_path, use_container_width=True)
    else:
        st.warning(f"File not found: {logo_text_path}")


with logocol2:
    # Define the image paths
    logos = [
        'partners/01.png',
        'partners/02.svg',
        'partners/03.svg',
        'partners/04.svg',
        'partners/05.png',
        'partners/06.png',
        'partners/datlab_logo.svg'
    ]

    # Create a 7-column layout
    columns = st.columns(7)

    # Inject CSS specifically for the partner logo columns
    # We make the direct child of the column a flex container and center items
    st.markdown("""
        <style>
        /* Target the containers generated by Streamlit for the columns */
        /* Adjust selector if needed based on Streamlit version / inspection */
        div[data-testid="stHorizontalBlock"] > div[data-testid="stVerticalBlock"] {
            display: flex;
            flex-direction: column;
            justify-content: center; /* Vertical centering */
            align-items: center; /* Horizontal centering */
            height: 100%; /* Make the container fill the column height */
            min-height: 50px; /* Optional: Ensure a minimum height for very small logos */
        }
        /* Control image size within the flex container */
        div[data-testid="stHorizontalBlock"] > div[data-testid="stVerticalBlock"] img {
            max-width: 100%; /* Ensure image fits horizontally */
            max-height: 50px; /* Set a maximum height for consistency! */
            object-fit: contain; /* Scale while preserving aspect ratio */
            margin: auto; /* Helps with centering */
        }
        </style>
    """, unsafe_allow_html=True)

    # Loop through each column and display the corresponding logo
    for i, col in enumerate(columns):
        with col:
            logo_path = logos[i]
            if Path(logo_path).is_file():
                st.image(logo_path) # Don't necessarily need use_container_width if using CSS max-width
            else:
                st.warning(f"File not found: {logo_path}")
col1,col2, = st.columns([10,5])
col1.subheader("")
col2.subheader("")
col2.subheader("Nastavení grafu")



year = col2.segmented_control("Rok",["2022","2023"],default="2023")
def USDtoCZKdefault(year):
    if year=="2022":
        return 23.360
    elif year=="2023":
        return 22.21

# Load data
@st.cache_data
def load_data(datayear):
    USD_to_czk = USDtoCZKdefault(datayear)
    # Replace with the path to your data file
    #df                          = pd.read_csv('GreenComplexity_CZE_2022.csv')
    url = 'https://docs.google.com/spreadsheets/d/1mhv7sJC5wSqJRXdfyFaWtBuEpX6ENj2c/gviz/tq?tqx=out:csv'
    taxonomy = pd.read_csv(url)
    CZE = pd.read_csv('CZE_'+datayear+'.csv')
    GreenProducts = taxonomy.merge(CZE,how='left',left_on='HS_ID',right_on='prod')
    # Calculate 2030 export value
    GreenProducts['CountryExport2030'] = GreenProducts['ExportValue'] * (1 + GreenProducts['CAGR_2022_30_FORECAST']) ** 8
    GreenProducts['EUExport2030'] = GreenProducts['EUExport'] * (1 + GreenProducts['CAGR_2022_30_FORECAST']) ** 8

    # Calculate Total Export Value from 2025 to 2030
    # We calculate for each datayear and sum up
    GreenProducts['CountryExport_25_30'] = sum(GreenProducts['ExportValue'] * (1 + GreenProducts['CAGR_2022_30_FORECAST']) ** i for i in range(3, 9))
    GreenProducts['EUExport_25_30'] = sum(GreenProducts['EUExport'] * (1 + GreenProducts['CAGR_2022_30_FORECAST']) ** i for i in range(3, 9))

    df = GreenProducts.rename(columns={'ExportValue': 'CZ Export '+datayear+' CZK',
                               'export_Rank':'Žebříček exportu CZ '+datayear+'',
                               'pci': 'Komplexita výrobku '+datayear+'',
                               'relatedness': 'Příbuznost CZ '+datayear+'',
                               'PCI_Rank':'Žebříček komplexity '+datayear+'',
                               'PCI_Percentile':'Percentil komplexity '+datayear+'',
                               'relatedness_Rank':'Žebříček příbuznosti CZ '+datayear+'',
                               'relatedness_Percentile':'Percentil příbuznosti CZ '+datayear+'',
                               'WorldExport':'Světový export '+datayear+' CZK',
                               'EUExport':'EU Export '+datayear+' CZK',
                               'EUWorldMarketShare':'EU Světový Podíl '+datayear+' %',
                               'euhhi':'Koncentrace evropského exportu '+datayear+'',
                               'hhi':'Koncentrace světového trhu '+datayear+'',
                               'CZE_WorldMarketShare':'CZ Světový Podíl '+datayear+' %',
                               'CZE_EUMarketShare':'CZ-EU Podíl '+datayear+' %',
                               'rca':'Výhoda CZ '+datayear+'',
                               'EUTopExporter':'EU Největší Exportér '+datayear+'',
                               'CZ_Nazev':'Název',
                               'CountryExport2030':'CZ 2030 Export CZK',
                               'EUExport2030':'EU 2030 Export CZK',
                               'CountryExport_25_30':'CZ Celkový Export 25-30 CZK',
                               'EUExport_25_30':'EU Celkový Export 25-30 CZK',
                               'CAGR_2022_30_FORECAST':'CAGR 2022-2030 Předpověď'
                               })
    df                          = df[df.Included == "IN"]
    df['stejna velikost']       = 0.02
    df['CZ-EU Podíl '+datayear+' %']      = 100 * df['CZ-EU Podíl '+datayear+' %'] 
    df['EU Světový Podíl '+datayear+' %'] = 100 * df['EU Světový Podíl '+datayear+' %'] 
    df['CZ Světový Podíl '+datayear+' %'] = 100 * df['CZ Světový Podíl '+datayear+' %'] 
    df['CZ Export '+datayear+' CZK']        = USD_to_czk*df['CZ Export '+datayear+' CZK'] 
    df['Světový export '+datayear+' CZK']      = USD_to_czk*df['Světový export '+datayear+' CZK'] 
    df['EU Export '+datayear+' CZK']        = USD_to_czk*df['EU Export '+datayear+' CZK'] 
    df['EU Celkový Export 25-30 CZK'] = USD_to_czk*df['EU Celkový Export 25-30 CZK'] 
    df['CZ Celkový Export 25-30 CZK'] = USD_to_czk*df['CZ Celkový Export 25-30 CZK'] 
    df['EU 2030 Export CZK']        = USD_to_czk*df['EU 2030 Export CZK'] 
    df['CZ 2030 Export CZK']        = USD_to_czk*df['CZ 2030 Export CZK'] 
    df['HS_ID']                 = df['HS_ID'].astype(str)
    df['HS_Lookup']              = df['HS_ID']+" - "+df['Název']
    
    st.sidebar.info(str(GreenProducts.shape[0]) + " HS6 načteno, z toho " +str(df.shape[0])+" je IN")
    return df


# Create lists of display names for the sidebar
year_placeholder = " ‎"
plot_display_names, hover_display_data = get_plot_and_hover_display_names(year_placeholder)
# Sidebar selection boxes using display names
x_axis      = col2.selectbox("Vyber osu X:", plot_display_names, index=4)
y_axis      = col2.selectbox("Vyber osu Y:", plot_display_names, index=5)
markersize  = col2.selectbox("Velikost dle:", plot_display_names, index=10)

df_2022 = load_data("2022")
df_2023 = load_data("2023")

if year=="2022":
    df = df_2022
if year=="2023":
    df = df_2023

# Apply filters to dataframe
filtered_df = df.copy()

filtrovat_dle_skupin = col2.toggle("Filtrovat dle kategorií",value=False)

if filtrovat_dle_skupin:
    color       = 'Kategorie'
    skupiny = df['Skupina'].unique()
    Skupina = col2.segmented_control('Skupina',skupiny,default=skupiny[5])
    filtered_df = filtered_df[filtered_df['Skupina'].isin([Skupina])]
else:
    color       = 'Skupina'


hover_info  = col2.multiselect("Co se zobrazí při najetí myší:", hover_display_data, default=['Název'])
col2.divider()
# Filter section
if 'filters' not in st.session_state:
    st.session_state.filters = []

subcol1, subcol2, subcol3 = col2.columns(3)
with subcol1:
    if st.button("Filtrování hodnot"):
        st.session_state.filters.append({'column': None, 'range': None})
with subcol2:
    if st.button("Odstranit filtry"):
        st.session_state.filters = []

# Display existing filters using display names
for i, filter in enumerate(st.session_state.filters):
    filter_col= col2.selectbox(f"Filtr {i+1}", plot_display_names, key=f"filter_col_{i}")
    filter_min, filter_max = df[filter_col.replace(year_placeholder,year)].min(), df[filter_col.replace(year_placeholder,year)].max()
    filter_range = col2.slider(f"Filtr {i+1}", float(filter_min), float(filter_max), (float(filter_min), float(filter_max)), key=f"filter_range_{i}")
    st.session_state.filters[i]['column'] = filter_col
    st.session_state.filters[i]['range'] = filter_range

# Apply numerical filters
for filter in st.session_state.filters:
    if filter['column'] is not None and filter['range'] is not None:
        filtered_df = filtered_df[
            (filtered_df[filter['column'].replace(year_placeholder,year)] >= filter['range'][0]) &
            (filtered_df[filter['column'].replace(year_placeholder,year)] <= filter['range'][1])
        ]

markersize = markersize.replace(year_placeholder,year)
x_axis = x_axis.replace(year_placeholder,year)
y_axis = y_axis.replace(year_placeholder,year)

# Replace negative values in markersize column with zero
filtered_df[markersize] = filtered_df[markersize].clip(lower=0)

# Remove NA values
filtered_df = filtered_df.dropna(subset=[x_axis, y_axis, color, markersize])


HS_select = st.multiselect("Filtrovat HS6 kódy",filtered_df['HS_Lookup'])

# Create a button in the sidebar that clears the cache
if st.sidebar.button('Obnovit Data'):
    load_data.clear()  # This will clear the cache for the load_data function
    st.sidebar.write("Sušenky vyčištěny!")
# Initialize the hover_data dictionary with default values of False for x, y, and markersize
#hover_data = {col: True for col in hover_info}
hover_data = get_hover_data(year,year_placeholder,hover_info,x_axis,y_axis,markersize)

if filtrovat_dle_skupin is True and Skupina is None:
    chart_js = None
elif HS_select == []:
    chart_js = chartjs_plot(filtered_df,markersize,hover_data,color,x_axis,y_axis,year)
else:
    chart_js = chartjs_plot(filtered_df[filtered_df['HS_Lookup'].isin(HS_select)],markersize,hover_data,color,x_axis,y_axis,year)

# Render the chart in Streamlit
html_bytes=chart_js
with col1:
    components.html(chart_js, height=800)

mcol1, mcol2, mcol3 = st.columns(3)
if HS_select == []:
    mcol1.metric("Vybraný český export za rok "+year+"", "{:,.0f}".format(sum(filtered_df['CZ Export '+year+' CZK'])/1000000000),'miliard CZK' )
    mcol2.metric("Vybraný český export 2025 až 2030", "{:,.0f}".format(sum(filtered_df['CZ Celkový Export 25-30 CZK'])/1000000000), "miliard CZK")
    mcol3.metric("Vybraný evropský export 2025 až 2030", "{:,.0f}".format(sum(filtered_df['EU Celkový Export 25-30 CZK'])/1000000000), "miliard CZK")

else:
    mcol1.metric("Vybraný český export za rok "+year+"", "{:,.0f}".format(sum(filtered_df[filtered_df['HS_Lookup'].isin(HS_select)]['CZ Export '+year+' CZK'])/1000000),'milionů CZK' )
    mcol2.metric("Vybraný český export 2025 až 2030", "{:,.0f}".format(sum(filtered_df[filtered_df['HS_Lookup'].isin(HS_select)]['CZ Celkový Export 25-30 CZK'])/1000000), "milionů CZK")
    mcol3.metric("Vybraný evropský export 2025 až 2030", "{:,.0f}".format(sum(filtered_df[filtered_df['HS_Lookup'].isin(HS_select)]['EU Celkový Export 25-30 CZK'])/1000000), "milionů CZK")



if filtrovat_dle_skupin is True and Skupina is None:
    pass
else:    
    subcol3.download_button(
        label = "Stáhnout HTML",
        data = html_bytes,
        file_name = "plot.html",
        mime="text/html"
    )

